use litesvm::LiteSVM;
use solana_sdk::{
    instruction::{AccountMeta, Instruction},
    pubkey::Pubkey,
    signature::{Keypair, Signer},
    transaction::Transaction,
    ed25519_instruction,
};
use anchor_lang::InstructionData;
use perp_dex::instruction as perp_ix; // Generated by Anchor

#[test]
fn test_full_hybrid_settlement_flow() {
    let mut svm = LiteSVM::new();
    let payer = Keypair::new();
    let engine_keypair = Keypair::new(); // The off-chain engine identity
    
    // 1. Setup Environment
    svm.airdrop(&payer.pubkey(), 10_000_000_000).unwrap();
    let program_id = Pubkey::new_unique();
    let program_bytes = include_bytes!("../target/deploy/perp_dex.so");
    svm.add_program(program_id, program_bytes);

    // 2. Initialize Engine Config
    let (config_pda, _) = Pubkey::find_program_address(&[b"engine_config"], &program_id);
    let init_ix = Instruction {
        program_id,
        accounts: vec![
            AccountMeta::new(config_pda, false),
            AccountMeta::new_readonly(payer.pubkey(), true),
            AccountMeta::new_readonly(solana_sdk::system_program::ID, false),
        ],
        data: perp_ix::Initialize { engine_signer: engine_keypair.pubkey() }.data(),
    };

    // 3. Simulate Off-Chain Match & Sign
    let trade_id = 101u64;
    let price = 150_000_000u64; // $150.00
    let qty = 1_000_000u64;      // 1.0 units
    
    // Reconstruct the message the engine signs
    let mut msg = Vec::new();
    msg.extend_from_slice(&trade_id.to_le_bytes());
    msg.extend_from_slice(&price.to_le_bytes());
    msg.extend_from_slice(&qty.to_le_bytes());
    
    // Engine signs it
    let sig = engine_keypair.sign(&msg).to_bytes();

    // 4. Create Ed25519 Verification Instruction (Instruction 0)
    let ed25519_ix = ed25519_instruction::new_ed25519_instruction(&engine_keypair, &msg);

    // 5. Create Settlement Instruction (Instruction 1)
    let settle_ix = Instruction {
        program_id,
        accounts: vec![
            AccountMeta::new_readonly(config_pda, false),
            AccountMeta::new(Pubkey::new_unique(), false), // buyer margin (mock)
            AccountMeta::new(Pubkey::new_unique(), false), // seller margin (mock)
            AccountMeta::new_readonly(solana_sdk::sysvar::instructions::ID, false),
        ],
        data: perp_ix::SettleTrade { 
            trade_id, price, quantity: qty, buyer_nonce: 0, seller_nonce: 0 
        }.data(),
    };

    // 6. Execute Transaction
    let tx = Transaction::new_signed_with_payer(
        &[ed25519_ix, settle_ix],
        Some(&payer.pubkey()),
        &[&payer],
        svm.latest_blockhash(),
    );

    let result = svm.send_transaction(tx);
    
    // If signature or price or margin failed, result will be Err
    assert!(result.is_ok(), "Settlement failed: {:?}", result.err());
}